### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tuxinal**
inform me if any change is needed

I'm not too sure about this line perhaps you could correct me on it?
> designed with the needs of Persian linux users in mind

### CODE REVIEW

**Comment by behdanisohrab** [comment]
thanks for your PR, The XFCE and Cinnamon versions are removed from development, Parch Currently ships with Plasma and Gnome

**Comment by tuxinal** [comment]
i updated this last night :)

**Comment by behdanisohrab** [comment]
Oh, ok i would take another look into it and if everything was ok i would merge it.

**Comment by tuxinal** [comment]
seems like there has been updates to the readme

**Pull request closed without merging**
